### PR TITLE
Pending suspicious surveys

### PR DESCRIPTION
**Pull request by lukebaker**
Matt,

This adds the functionality described here: https://www.pivotaltracker.com/story/show/110253444

If a wiki survey is created with ideas that looks spammy (for now we're only checking to see if the ideas include things that could be URLs), then the following things happen:

1. The admin is redirected to /verify which includes a note about needing to activate their wiki survey.
2. The wiki survey is disabled until the user verifies their email.
3. The email we send to an admin after they create a wiki survey now includes the verify link if the wiki survey requires verification.

There were some additional changes in this branch to get Travis CI working again fully after they made some updates to their systems.

### CODE REVIEW

**Comment by msalganik** [comment]
Luke, 

Can you describe more clearly the conditions that trigger the verify page?

For example, I created one with 3 urls and it did not ask me to verify: http://spreadsomething.net/spam?just_created=true

**Comment by lukebaker** [comment]
> Can you describe more clearly the conditions that trigger the verify page?

Right now the code is simply looking for the string 'http' in any of the ideas. The spammers are hoping that the values they input will result in HTML output that includes links, so they need to include a valid full URL which generally will include 'http'. This is what I've been using to identify spam wiki surveys in the past and it has worked well enough for that despite its unsophistication.

**Comment by msalganik** [comment]
Great.  That seems to work.

Two questions about the code:
1) is the part that checks and diverts to the verification modular?  This is a part of the code that I expect that we could update in the future, and so it should probably be modular and clear.
2) What tests do we have for this new feature?  If was hard to tell from the pull request because it looks like there were some other issues with the tests.

**Comment by lukebaker** [comment]
> is the part that checks and diverts to the verification modular? This is a part of the code that I expect that we could update in the future, and so it should probably be modular and clear.

Yes, the logic for that is primarily in the `earl` model. https://github.com/allourideas/allourideas.org/pull/34/files#diff-6b1aa61bd4c3783b27767f5db362e1e4R35

The other aspects of the code call these methods (e.g., redirect to verification page if earl.requires_verification? is true, etc.)

> What tests do we have for this new feature? If was hard to tell from the pull request because it looks like there were some other issues with the tests.

I've added tests that should cover this feature pretty well:

* https://github.com/allourideas/allourideas.org/pull/34/files#diff-102bbc69cb5d5234274f794a979ddb99
* https://github.com/allourideas/allourideas.org/pull/34/files#diff-2918028a2fb85a17071258814ad809fd

**Comment by msalganik** [comment]
Great.  I'm approval on pivotal.  Please merge and deploy when you think it makes sense.

**Comment by msalganik** [comment]
Ooops.  I'll approve on pivotal once you mark it finished and delivered.

**Pull request merged**
